### ISSUE TITLE
Feature - ability to hand over a replace to a delegate function

### ISSUE THREAD

**Issue by jafin** [WordDocX/DocX#10]
It would be useful to hand over the Replace to accept a delegate that can do work against regex matches, for example in a mailmerge scenario.

**Comment by jafin** [comment]
Thanks

**Comment by PrzemyslawKlys** [comment]
Just one thing. There seems to be similar commit done on Codeplex..

https://docx.codeplex.com/workitem/13831
https://docx.codeplex.com/workitem/13827

Can you take a look if those changes can be merged together with your last commit?

**Comment by PrzemyslawKlys** [comment]
Nevermind. It's applied already.
