### ISSUE TITLE
Section PageLayout Orientation

### ISSUE THREAD

**Issue by GlenConway** [WordDocX/DocX#110]
Hi - I'd like to have a document in two sections where the first section is Landscape and the second is Portrait. 

The following code does not produce the expected result, both pages of the document are portrait:

```
using (DocX document = DocX.Create(Path.Combine(_directoryDocuments, "ChangePageLayoutOrientationAfterSectionPageBreak.docx")))
            {
                document.PageLayout.Orientation = Orientation.Landscape;
                document.InsertParagraph("Should be landscape.");
                
                document.InsertSectionPageBreak();

                document.PageLayout.Orientation = Orientation.Portrait;
                document.InsertParagraph("Should be portrait.");
                
                document.Save();
            }
```
I couldn't see a PageLayout property on the section and wonder if my code is correct.

Thanks!

**Comment by GlenConway** [comment]
I tried to add this but gave up after a couple of days. For my immediate needs I decided to take inspiration from this project and [create an abstraction around the Open XML SDK](https://github.com/GlenConway/DocXPlus) It's nowhere near as well featured as DocX but it serves my purpose.

**Comment by PrzemyslawKlys** [comment]
This is actually possible. You do it by creating new document (for example document2) and adding all the new stuff to it and then doing `document.InsertDocument(document2)` after `document.InsertSectionPageBreak`
