### ISSUE TITLE
Potential bug in HelperFUnctions::IsSameFile()

### ISSUE THREAD

**Issue by Wayne-Mather** [WordDocX/DocX#13]
On line 641 of internal static bool IsSameFile(Stream streamOne, Stream streamTwo) 

```
            if (streamOne.Length != streamOne.Length)
            {
                // Return false to indicate files are different
                return false;
            }
```

Is there any reason to check if the length of the same stream does not match? Should not one of those be streamTwo?

**Comment by PrzemyslawKlys** [comment]
Fixed. Thank you.

**Comment by Wayne-Mather** [comment]
No Problems. Looks like there maybe a few more from me as the unit tests are not right due to the use bool? data types

**From**
`Assert.IsTrue(boldTextFormatting.Bold);`

**To**
`Assert.IsTrue(boldTextFormatting.Bold.HasValue && boldTextFormatting.Bold.Value);`

**Comment by PrzemyslawKlys** [comment]
Yes. fitdev added some changes recently and it fails on UnitTests due to change bool to bool?

**Comment by PrzemyslawKlys** [comment]
fixed according to your suggestion. Thank you again
