### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by lacvapps** [WordDocX/DocX#18]
here is my code
            Image img = doc.AddImage(@".\images\test.jpg");
            Picture pic = img.CreatePicture();
            pic.Height = 100;
            pic.Width = 200;
            Paragraph p = doc.InsertParagraph("", false);
            pic.SetPictureShape(RectangleShapes.rect);
            p.InsertPicture(pic);
            
            doc.SaveAs($"{path}\\src\\newDoc.docx");

when executed the document is saved and the image is placed on the bottom but it is a blank image.

**Comment by PrzemyslawKlys** [comment]
Seems fine to me. I've created a sample for you. Also committed it to sources.

http://evotec.pl/docx-add-image-to-microsoft-word-document-programmatically/
