### ISSUE TITLE
New to github

### ISSUE THREAD

**Issue by cradaydg** [WordDocX/DocX#27]
I've added a collection for Content Controls and a couple of methods for replacing text in the, It's on my fork, but I'm very new to GitHub and I'm unsure what to do from here. Help, please?

**Comment by PrzemyslawKlys** [comment]
Hard to say :-) I guess you have to create Pull request and add it there, or just point me where it is and I can try to merge it somehow :-)

**Comment by PrzemyslawKlys** [comment]
Applied your sources  but you should update the example a bit. I have no document you used in examples so right now it's commented out.
