### ISSUE TITLE
Provide a copy constructor for DocX

### ISSUE THREAD

**Issue by CPonty** [WordDocX/DocX#3]
doc.Copy(): create a new DocX object from an existing one. 

Can be done pretty easily by copying the underlying document content via memory stream.

Something like this:

```C#
DocX doc;
var stream= new MemoryStream();

/* some code to populate the document */

doc.SaveAs(stream);
stream.Seek(0, SeekOrigin.Begin);

DocX doc2= DocX.Load(stream);
```

https://docx.codeplex.com/workitem/13710

**Comment by CPonty** [comment]
Ready: pull https://github.com/WordDocX/DocX/pull/4

**Comment by PrzemyslawKlys** [comment]
Commited. Thank you :-)
