### ISSUE TITLE
Just need some help.

### ISSUE THREAD

**Issue by mfahadi** [WordDocX/DocX#30]
I am using DocX and it is a great library, very powerful. I generate dynamic docs with it and worked great.

Now I have a block of html and I want to add that in an existing doc, while keeping all the formatting, like b /br font size h1 etc, I want to know how can I do that with DocX or I need to use some other library.
Thanks

**Comment by PrzemyslawKlys** [comment]
I don't think HTML is supported now. There were talks about it. But nothing was implemented I believe.
