### ISSUE TITLE
Set Table with w.r.t. Percentage.

### ISSUE THREAD

**Issue by kanadmehta** [WordDocX/DocX#42]
I have tested method for same.

`/// <summary>
        /// Set Table column width by prescribing percent
        /// </summary>
        /// <param name="widthsPercentage">column width % list</param>
        /// <param name="totalWidth">Total table width. Will be calculated if null sent.</param>
        public void SetWidthsPercentage(float[] widthsPercentage, float? totalWidth)
        {
            if (totalWidth == null) totalWidth = this.Document.PageWidth - this.Document.MarginLeft - this.Document.MarginRight; // calculate total table width
            List<float> widths = new List<float>(widthsPercentage.Length); // empty list, will hold actual width
            widthsPercentage.ToList().ForEach(pWidth => { widths.Add(pWidth * totalWidth.Value / 100); }); // convert percentage to actual width for all values in array
            SetWidths(widths.ToArray()); // set actual column width
        }`

Can be added to Table class

**Comment by PrzemyslawKlys** [comment]
Why not add it to sources so we can simply commit? Right now it's unreadable.

**Comment by PrzemyslawKlys** [comment]
Added to sources.
