### ISSUE TITLE
HelperFunctions.FormatInput doubles new lines

### ISSUE THREAD

**Issue by janbernloehr** [WordDocX/DocX#44]
If one adds a multi-line string using Paragraph.Append, AppendLine, InsertText, ReplaceText, ..., for each new line in actually two new lines are added to the document.

The reason is how strings a formatted in HelperFunctions.FormatInput. Enviroment.NewLine (on Windows) corresponds to '\r\n'. Before 1.0.0.20 only '\n' was considered as a special character adding a new line. However, in 24dd8ee25d88478ba27281f26c91a6d8d538b61e also '\r' was given a special character treatment to issue a new line. Thus a standard Environment.NewLine = '\r\n' now causes two line breaks to be added to the document.

A workaround is to use Replace("\r\n", "\n") on a given string before passing it to Append, AppendLine, InsertText, ReplaceText, ... of a Paragraph, however this appears a little awkward.

**Comment by PrzemyslawKlys** [comment]
What would you suggest as a fix?

**Comment by janbernloehr** [comment]
I created a PR https://github.com/WordDocX/DocX/pull/45

**Comment by PrzemyslawKlys** [comment]
Commited.
