### ISSUE TITLE
DOCX in china

### ISSUE THREAD

**Issue by CPonty** [WordDocX/DocX#57]
Looks like there is no support for the Chinese character set:

```
public Paragraph Font(FontFamily fontFamily)
        {
            ApplyTextFormattingProperty
            (
                XName.Get("rFonts", DocX.w.NamespaceName),
                string.Empty,
                new[] 
                {
                    new XAttribute(XName.Get("ascii", DocX.w.NamespaceName), fontFamily.Name),
                    new XAttribute(XName.Get("hAnsi", DocX.w.NamespaceName), fontFamily.Name), // Added by Maurits Elbers to support non-standard characters. See http://docx.codeplex.com/Thread/View.aspx?ThreadId=70097&ANCHOR#Post453865
                    new XAttribute(XName.Get("cs", DocX.w.NamespaceName), fontFamily.Name),    // Added by Maurits Elbers to support non-standard characters. See http://docx.codeplex.com/Thread/View.aspx?ThreadId=70097&ANCHOR#Post453865
                }
            );

            return this;
        }
```

Adding support should be as simple as:

```
new XAttribute(XName.Get("eastAsia", DocX.w.NamespaceName), fontFamily.Name)
```

**Comment by ichpuchtli** [comment]
DocX is yuuge in china.

**Comment by PrzemyslawKlys** [comment]
@CPonty feel free to submit pull request :-)

**Comment by PrzemyslawKlys** [comment]
If possible please create a test case as well with chinese document or so.

**Comment by neights** [comment]
@ichpuchtli   ah........  what is yuuge???  yuuge.......
DocX  is very popular in China
I used it in a lot of projects to generate docx files 
so cool......

**Comment by neights** [comment]
@CPonty   i'm ice ,Thanks for your reply
this is my new GitHub Account
After study together

**Comment by ichpuchtli** [comment]
@neights don't worry yuuge is an joke with my colleague @CPonty. I'm sure DocX is huge in china. I think @CPonty should make a pull request.

**Comment by wuchao288** [comment]
根据 CPonty 的指导， DocX设置中文字体无效的修正方法，可以把作者的项目下载修改后再编译,期待作者nuget上更新.
I changed the code  like this
 `public Paragraph Font(FontFamily fontFamily)
        {
            ApplyTextFormattingProperty
            (
                XName.Get("rFonts", DocX.w.NamespaceName),
                string.Empty,
                new[] 
                {
                    new XAttribute(XName.Get("eastAsia", DocX.w.NamespaceName), fontFamily.Name),
                    new XAttribute(XName.Get("ascii", DocX.w.NamespaceName), fontFamily.Name),
                    new XAttribute(XName.Get("hAnsi", DocX.w.NamespaceName), fontFamily.Name), 
                    new XAttribute(XName.Get("cs", DocX.w.NamespaceName), fontFamily.Name)
                }
            );
            return this;
            // Paragraph p2 = document.InsertParagraph("参考行程", false);
            // p2.FontSize(20).Font(new FontFamily("黑体"));
        }`
@CPonty   thank you!

**Comment by PrzemyslawKlys** [comment]
I am not sure why you guys couldn't commit this change as normal change. Added and closin this topic.
