### ISSUE TITLE
FontSize in Paragraph.cs does not allow for half-sizes (ex. 7.5)

### ISSUE THREAD

**Issue by lukewalshct** [WordDocX/DocX#63]
The FontSize() method in Paragraph.cs does not allow for half sizes, and an exception is thrown erroneously. I believe this is because of the if logic in line 2969  if (fontSize - (int)fontSize == 0).

This should be a quick fix and I'll submit a pull request shortly. Adding to issues list for documentation.

**Comment by PrzemyslawKlys** [comment]
Thanks, merged.
