### ISSUE TITLE
How to reference  nameof？

### ISSUE THREAD

**Issue by t1o4m5** [WordDocX/DocX#65]

**Comment by mkorsukov** [comment]
nameof operator is a syntax sugar to get an instance variable name. It supports by latest C# compiler. What I found, the solution itself references Visual Studio 2015 (v14) and VS compiles this code fine. However, the project targets .NET 3.5 and this is a problem for the previous version of VS. A couple of fix ideas:
- Open solution in VS 2015 or use MsBuild 2015 to compile it
- Upgrade all projects to .NET 4.5

**Comment by mkorsukov** [comment]
You know, the DocX project targets .NET 3.5, other projects - .NET 4.0

**Comment by t1o4m5** [comment]
Thank
