### ISSUE TITLE
Script property not parsed

### ISSUE THREAD

**Issue by lucwuyts** [WordDocX/DocX#69]
This code should be added to the Parse function in Formatting.cs
`case "vertAlign":`
`                        var script = option.GetAttribute(XName.Get("val", DocX.w.NamespaceName), null);`
`                       formatting.Script = (Script)Enum.Parse(typeof(Script), script);`
`                        break;`

**Comment by PrzemyslawKlys** [comment]
Added. Please verify. If possible please send some unit tests for this / examples of usage. Thank you
