### ISSUE TITLE
Strings are reversed

### ISSUE THREAD

**Issue by amirgalor** [WordDocX/DocX#7]
The following code generates a document in which the strings are reversed...
using the latest NuGet - version DocX.1.0.0.19

- reversing strings does not help entirely
- applying styles such as bold/etc is harder...

```
public static void DocumentHeading()
        {
            Console.WriteLine("\tDocumentHeading()");
            using (DocX document = DocX.Create(@"C:\TEMP\DocumentHeading.docx"))
            {

                foreach (HeadingType heading in (HeadingType[])Enum.GetValues(typeof(HeadingType)))
                {
                    string text = string.Format("{0} - The quick brown fox jumps over the lazy dog", heading.EnumDescription());

                    Paragraph p = document.InsertParagraph();
                    p.AppendLine(text).Heading(heading);
                }


                document.Save();
                Console.WriteLine("\tCreated: docs\\DocumentHeading.docx\n");
            }
        }
```

**Comment by jafin** [comment]
@amirgalor I ran your example in 1.0.0.21 and it _appears_ correct. Perhaps I'm either misunderstanding your issue or it was fixed since .19 
![output2](https://cloud.githubusercontent.com/assets/127927/12804003/c582e594-cb3a-11e5-828a-205e55ff9055.png)

**Comment by PrzemyslawKlys** [comment]
Closing as the NuGet is outdated and as per jafin comment it seems everything is ok.
