### ISSUE TITLE
Setting IndentationBefore and IndentationAfter makes an error when decimalsign is not a dot

### ISSUE THREAD

**Issue by lucwuyts** [WordDocX/DocX#70]
I live in Belgium, and our decimal sign is a komma
The setter for IndentationBefore and IndentationAfter makes a invalid xml string  (Word 2016 has a problem reading this, LibreOffice 5 does read it correct)

This is the xml generated:

`<w:ind w:left="706,800005435944" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" />
`

Solution: 
Change line 785 and 728  from this:
`string indentation = ((indentationBefore / 0.1) * 57).ToString();`

to this:
`string indentation = ((indentationBefore / 0.1) * 57).ToString(CultureInfo.GetCultureInfo("en-GB"));`

**Comment by PrzemyslawKlys** [comment]
Commited to sources. Thanks. Wouldn't it be easier to provide this as a pull request ?:)

**Comment by lucwuyts** [comment]
Probably, but i have no experience doing this.

**Comment by PrzemyslawKlys** [comment]
http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request
