### ISSUE TITLE
sample with list

### ISSUE THREAD

**Issue by rodrigoporcionato** [WordDocX/DocX#8]
Hi,

How to create a list like a invoice with products?

I need like this sample http://www.e-iceblue.com/Tutorials/Spire.Doc/Spire.Doc-Program-Guide/How-to-Use-Mail-Merge-to-Create-Report.html

thanks

**Comment by PrzemyslawKlys** [comment]
You have that example in the source codes under Examples. It should be possible to do most of it if not all. There is even "invoice" example in Source Codes.
