### ISSUE TITLE
getting/setting picture height/width

### ISSUE THREAD

**Issue by ermoll** [WordDocX/DocX#84]
getting height/width from Picture is done by cx/emusinpixel or cy/emusinpixel but when setting 
the code set cx / cy to given value and alter the xml code to (cx * emusinpixel) or (cy * emusinpixel)

so when setting the width to 100 = cx is set 100  and xml to 100 * emusinpixel
but when getting this same width returned is cx/emusinpixel = 100/emusinpixel thus not correct !

on set of width / height the cx/cy must be  calculated as value * emusinpixel and set this value in the xmlcode OR on the get there should be no divide by emusinpixel.

>>
 public int Width 
        { 
            get { return cx / EmusInPixel; }
            
            set 
            { 
                **cx = value * EmusInPixel;**

                foreach (XAttribute a in Xml.Descendants().Attributes(XName.Get("cx")))
                    a.Value = (cx).ToString();
            } 
        }

        /// <summary>
        /// Get or sets the height of this Image.
        /// </summary>
        public int Height 
        { 
            get { return cy / EmusInPixel; }
            
            set 
            { 
                **cy = value * EmusInPixel;**

                foreach (XAttribute a in Xml.Descendants().Attributes(XName.Get("cy")))
                    a.Value = (cy).ToString();
            } 
        }

<<

**Comment by PrzemyslawKlys** [comment]
ermoll can you please provide patch for this?

**Comment by ermoll** [comment]
alter the set/get statement like in my message [without the ** ofcourse] ....or you want a file or something? 
BTW: I;'ve added another patch in Paragraph.cs  in CreatePicture on finding the next newDocPrId

**Comment by PrzemyslawKlys** [comment]
I mean creating a pull request. Then I can simply approve it and it's added to main sources.

**Comment by ermoll** [comment]
done...i hope properly :-)

**Comment by PrzemyslawKlys** [comment]
Yep, great. Commited :)
